// src-next/components/ui/button.tsx
"use client";

import { forwardRef } from "react";
import type { ButtonHTMLAttributes } from "react";

import { cn } from "@/lib/utils";

type ButtonVariant = "default" | "ghost" | "outline" | "subtle" | "danger";
type ButtonSize = "sm" | "md" | "lg" | "icon";

export type ButtonProps = {
  variant?: ButtonVariant;
  size?: ButtonSize;
} & ButtonHTMLAttributes<HTMLButtonElement>;

const VARIANT_STYLES: Record<ButtonVariant, string> = {
  default:
    "bg-slate-900/90 text-white hover:bg-slate-900/80 focus-visible:ring-slate-300",
  ghost:
    "bg-white/0 text-slate-700 hover:bg-white/50 focus-visible:ring-slate-300",
  outline:
    "border border-white/60 bg-white/60 text-slate-800 hover:bg-white/80 focus-visible:ring-slate-300",
  subtle:
    "bg-white/60 text-slate-800 hover:bg-white/70 focus-visible:ring-slate-300",
  danger:
    "bg-red-500 text-white hover:bg-red-600 focus-visible:ring-red-300",
};

const SIZE_STYLES: Record<ButtonSize, string> = {
  sm: "h-9 px-3 text-sm",
  md: "h-10 px-4 text-sm",
  lg: "h-12 px-5 text-base",
  icon: "h-10 w-10",
};

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    { className, variant = "default", size = "md", type = "button", ...props },
    ref,
  ) => (
    <button
      ref={ref}
      type={type}
      className={cn(
        "inline-flex cursor-pointer items-center justify-center rounded-xl font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:pointer-events-none disabled:opacity-60",
        VARIANT_STYLES[variant],
        SIZE_STYLES[size],
        className,
      )}
      {...props}
    />
  ),
);

Button.displayName = "Button";

// src/components/ui/Button.vue
<script setup lang="ts">
import { computed } from "vue";

import { cn } from "@/lib/utils";

type ButtonVariant = "default" | "ghost" | "outline" | "subtle" | "danger";
type ButtonSize = "sm" | "md" | "lg" | "icon";

const VARIANT_STYLES: Record<ButtonVariant, string> = {
  default:
    "bg-slate-900/90 text-white hover:bg-slate-900/80 focus-visible:ring-slate-300",
  ghost:
    "bg-white/0 text-slate-700 hover:bg-white/50 focus-visible:ring-slate-300",
  outline:
    "border border-white/60 bg-white/60 text-slate-800 hover:bg-white/80 focus-visible:ring-slate-300",
  subtle:
    "bg-white/60 text-slate-800 hover:bg-white/70 focus-visible:ring-slate-300",
  danger: "bg-red-500 text-white hover:bg-red-600 focus-visible:ring-red-300",
};

const SIZE_STYLES: Record<ButtonSize, string> = {
  sm: "h-9 px-3 text-sm",
  md: "h-10 px-4 text-sm",
  lg: "h-12 px-5 text-base",
  icon: "h-10 w-10",
};

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant;
    size?: ButtonSize;
    type?: "button" | "submit" | "reset";
  }>(),
  {
    variant: "default",
    size: "md",
    type: "button",
  },
);

const buttonClass = computed(() =>
  cn(
    "inline-flex cursor-pointer items-center justify-center rounded-xl font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:pointer-events-none disabled:opacity-60",
    VARIANT_STYLES[props.variant],
    SIZE_STYLES[props.size],
  ),
);
</script>

<template>
  <button :type="props.type" :class="buttonClass" v-bind="$attrs">
    <slot />
  </button>
</template>
